# ~/.streamlit/config.toml

[server]
# Specify the port for Streamlit to run on
port = 8501
# Allow access to Streamlit app from any IP address (useful for VPS setup)
headless = true
# Disable the browser auto-launch when the app starts
open_browser = false
# Set the address to allow connections from any host
address = "0.0.0.0"

[browser]
# Disable the auto-opening of a new tab in the browser when running the app
serverAddress = "162.43.50.71"

[theme]
base="dark"
font = "sans serif"

[runner]
fastReruns = false